CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE superman WITH LOGIN PASSWORD 'superman' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE money_transaction_database;
GRANT ALL PRIVILEGES ON DATABASE money_transaction_database TO superman ;
GRANT ALL PRIVILEGES ON DATABASE money_transaction_database TO super;